---
title: "EDA HW#8"
author: "Tonghao Zhang"
date: "2016/11/9"
output: pdf_document
---

```{r lval,include=FALSE}
lvalue<-function(x,na.rm=TRUE){
  xna<-is.na(x)
  if(na.rm) 
    x<-x[!xna]
  else if(any(xna)) 
    return(rep(NA,5))
  x<-sort(x)
  n<-length(x)
  cpos<-n
  depth<-c()
  while(cpos>1){
    cpos<-(floor(cpos)+1)/2
    if(cpos!=1.5) 
      depth<-c(depth,cpos)
  }
  lo<-(x[floor(depth)]+x[ceiling(depth)])/2
  hi<-(x[floor(n+1-depth)]+x[ceiling(n+1-depth)])/2
  mids<-(lo+hi)/2
  spreads<-hi-lo
  out=data.frame(depth,lo,hi,mids,spreads)
  labels=c("M","F","E","D","C","B","A","Z","Y","X",rep("",1000))
  row.names(out)=labels[1:length(dimnames(out)[[1]])]
  return(out)
}
```

##Ex 2

```{r 2,echo=FALSE,fig.height=3}
data2<-c(1092,1137,1197,1237,1301,1523,1577,1619,1626,1644,1672,1748,1768,1780,1796,1816,1843,1844,1902,1919,1983,1993,2025,2028,2032,2036,2072,2078,2090,2137,2162,2163,2180,2185,2194,2225,2230,2233,2234,2235,2265,2270,2274,2281,2289,2319,2322,2357,2381,2398,2421,2421,2443,2522,2549,2552,2581,2618,2618,2620,2624,2642,2647,2666,2705,2721,2740,2804,2819,2823,2860,2873,2906,2913,2926,2929,2931,2931,2934,2939,2961,3020,3023,3044,3047,3048,3096,3174,3190,3199,3204,3222,3225,3278,3287,3292,3300,3339,3361,3412,3462,3503,3530,3589,3672,3734,3749,3783,3854,3901,3932,3995,4001,4006,4118,4134,4320,4346,4385,4401,4522,4565,4581,4593,4629,4855,4868,4878,4885,4907,4962,4975,5021,5127,5155,5160,5183,5229,5242,5379,5383,5513,5555,5619,5755,5774,5890,5899,5988,6161,6185,6818,7406,7419,8175,8220,8282,8827,9027,9042,9805)

library(ggplot2)
qqplot.data<-function(vec) # argument: vector of numbers
{
  # following four lines from base R's qqline()
  y<-quantile(vec[!is.na(vec)],c(0.25, 0.75))
  x<-qnorm(c(0.25, 0.75))
  slope<-diff(y)/diff(x)
  int<-y[1L]-slope*x[1L]

  d<-data.frame(resids=vec)
  ggplot(d,aes(sample=resids))+stat_qq()+geom_abline(slope=slope,intercept=int)
}

qqplot.data(data2)
```

The QQ-plot shows the distribution appears skewed.

```{r 2.2, echo=FALSE,fig.height=2.8}
A<-median(data2)
lval<-lvalue(data2)
ratio<-(lval$hi-A)/(A-lval$lo)
quantile<-(1:8)
quantile<-2^(-quantile)
quantile<-qnorm(quantile)
ghat<-log(ratio)/(-quantile)
data2.2<-data.frame(x=c(1:8),y=ghat)
ggplot(data2.2,aes(x=x,y=y))+geom_point()+labs(y="ghat")
G<-median(ghat,na.rm = T)
xx<-(exp(G*quantile)-1)/G

rrline1<-function(x,y){
n<-length(x);nmod3<-n%%3;
if(nmod3==0) 
  n3<-n/3;
if(nmod3==1) 
  n3<-(n-1)/3;
if(nmod3==2) 
  n3<-(n+1)/3;
x.order<-order(x)
medxL<-median(x[x.order][1:n3])
medxR<-median(rev(x[x.order])[1:n3])
medyL<-median(y[x.order][1:n3])
medyR<-median(rev(y[x.order])[1:n3])
slope1<-(medyR-medyL)/(medxR-medxL)
int1<-median(y-slope1*x)
newy<-y-slope1*x-int1
sumres<-sum(abs(newy))
return(list(a=int1,b=slope1,sumres=sumres,res=newy))
}

run.rrline<-function(xx,yy,iter=5){
out.coef<-matrix(0,iter,3)
ll<-(1:length(xx))[!is.na(xx)&!is.na(yy)]
n<-length(ll);x<-xx[ll];y<-yy[ll];newy<-y
for(i in 1:iter){
  rr<-rrline1(x,newy)
  out.coef[i,]<-c(rr$a,rr$b,rr$sumres)
  newy<-rr$res
  }
dimnames(out.coef)<-list(format(1:iter),c("a","b","|res|"))
aa<-sum(out.coef[, 1]);bb<-sum(out.coef[, 2]);cc<-sum(abs(y-aa-bb*x))
res<-yy-aa-bb*xx
out.coef<-rbind(out.coef, c(aa, bb, cc))
#print(round(out.coef,5))
return(list(a=aa, b=bb,res=res,coef=out.coef))
}

RRfit2<-run.rrline(xx,lval$lo)
data2.2<-data.frame(x=xx,y=lval$lo)
ggplot(data2.2,aes(x=x,y=y))+geom_point()+geom_abline(slope=RRfit2$b,intercept=RRfit2$a)
```

I estimated A to be `r RRfit2$a`, B to be `r RRfit2$b`, g to be `r G`.

```{r 2.3,echo=FALSE,fig.height=2.8}
bt<-matrix(0,nrow=200,ncol=3)
for(i in 1:200){
  ii<-sample(c(1:161),161,replace = TRUE)
  data2.3<-data2[ii]

  A<-median(data2.3)
  lval<-lvalue(data2.3)
  ratio<-(lval$hi-A)/(A-lval$lo)
  quantile<-(1:8)
  quantile<-2^(-quantile)
  quantile<-qnorm(quantile)
  ghat<-log(ratio)/(-quantile)
  G<-median(ghat,na.rm = T)
  xx<-(exp(G*quantile)-1)/G

  RRfit2.3<-run.rrline(xx,lval$lo)
  
  bt[i,]<-c(G,RRfit2.3$a,RRfit2.3$b)
}
colnames(bt)<-c("g","A","B")
bt.est<-apply(bt,2,mean)
bt.sd<-apply(bt,2,sd)
tvalue<-qt(0.95,199)
CI<-matrix(0,ncol = 3,nrow = 2)
CI[1,]<-bt.est-tvalue*bt.sd
CI[2,]<-bt.est+tvalue*bt.sd
colnames(CI)<-c("g","A","B")
rownames(CI)<-c("lower","upper")
CI
cor(bt)
pairs(bt)
```



```{r 2.4,echo=FALSE,fig.height=2.6}
Yg<-(data2-bt.est[2])/bt.est[3]
data2.4<-log(Yg*bt.est[1]+1)/bt.est[1]
qqplot.data(data2.4)
```

The transformed data looks less skewed.

##Ex 3

```{r 3,echo=FALSE,fig.height=2.6}
data3<-read.table("eda8.txt")
data3<-as.matrix(data3)
data3<-c(t(data3))
data3<-data3[1:161]
qqplot.data(data3)
```

The data appear to be long-tailed compared to Gaussian.

```{r 3.1, echo=FALSE,fig.height=2.6}
lval<-lvalue(data3)
yy<-(lval$hi-lval$lo)/(-2*quantile)
yy<-yy[2:8]
xx<-(quantile^2/2)
xx<-xx[2:8]
RRfit3<-run.rrline(xx,log(yy))
data3.1<-data.frame(x=xx,y=log(yy))
ggplot(data3.1,aes(x=x,y=y))+geom_point()+geom_abline(slope = RRfit3$b,intercept = RRfit3$a)
a<-c(RRfit3$b,median(data3),exp(RRfit3$a))
names(a)<-c("h","A","B")
a
```

```{r 3.2,echo=FALSE,fig.height=3}
bt<-matrix(0,nrow = 200,ncol = 3)
for(i in 1:200){
  ii<-sample(c(1:161),161,replace = TRUE)
  data3.2<-data3[ii]
   
  lval<-lvalue(data3.2)
  yy<-(lval$hi-lval$lo)/(-2*quantile)
  yy<-yy[2:8]
  xx<-(quantile^2/2)
  xx<-xx[2:8]
  RRfit3.2<-run.rrline(xx,log(yy))
  
  bt[i,]<-c(RRfit3.2$b,median(data3.2),exp(RRfit3.2$a))
}

colnames(bt)<-c("h","A","B")
bt.est<-apply(bt,2,mean)
bt.sd<-apply(bt,2,sd)
tvalue<-qt(0.95,199)
CI<-matrix(0,ncol = 3,nrow = 2)
CI[1,]<-bt.est-tvalue*bt.sd
CI[2,]<-bt.est+tvalue*bt.sd
colnames(CI)<-c("h","A","B")
rownames(CI)<-c("lower","upper")
CI
cor(bt)
pairs(bt)
```

